# yaml-language-server: $schema=ai.yaml.json

deployments:
  - name: openai-text-embedding-ada-002
    platform: openai
    roles:
      - embedding
    model:
      format: OpenAI
      api: embeddings
      name: text-embedding-ada-002
      version: "2"
    sku:
      name: "Standard"
      capacity: 100
    regions:
      - westus3
      - northcentralus
  - name: meta-llama-3-1-405B-chat
    platform: serverless
    roles:
      - teacher
    model:
      api: chat
      registry: azureml-meta
      name: Meta-Llama-3.1-405B-Instruct
    regions:
      - westus3
  - name: meta-llama-2-7b-chat
    platform: serverless
    roles:
      - student
      - baseline
    model:
      api: chat
      registry: azureml-meta
      name: Meta-Llama-3.1-8B-Instruct
    regions:
      - westus3
  - name: openai-gpt-4
    platform: openai
    roles:
      - teacher
    model:
      api: chat
      format: OpenAI
      name: gpt-4
      version: "turbo-2024-04-09"
    sku:
      name: "GlobalStandard"
      capacity: 8
    regions:
      - northcentralus
  - name: openai-gpt-4o
    platform: openai
    roles:
      - teacher
    model:
      api: chat
      format: OpenAI
      name: gpt-4o
      version: "2024-05-13"
    sku:
      name: "GlobalStandard"
      capacity: 8
    regions:
      - northcentralus
  - name: openai-gpt-4o-mini
    platform: openai
    roles:
      - student
      - baseline
    model:
      api: chat
      format: OpenAI
      name: gpt-4o-mini
      version: "2024-07-18"
    sku:
      name: "GlobalStandard"
      capacity: 8
    regions:
      - northcentralus
